apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: jenkins-workshop-templates
  description: A collection of RHDH templates for Jenkins RHTAP Workshop
spec:
  type: url
  targets:
     - scaffolder-templates/quarkus-insecure-jenkins-template/template.yaml
     - scaffolder-templates/quarkus-secure-jenkins-template/template.yaml
     - scaffolder-templates/quarkus-secure-tekton-template/template.yaml
